// Endpoints

// Default endpoint for the client
###
GET http://localhost:5000/


// Get All books
###
GET http://localhost:5000/api/books

// Get a book by ID
###
GET http://localhost:5000/api/books/4

// Add a new book
###
POST http://localhost:5000/api/books
Content-Type: application/json

{
    "title": "1",
    "author": "w",
    "year": 2023,
    "genre": "1"
}

// Update a book by ID
###
PUT http://localhost:5000/api/books/4
Content-Type: application/json

{
    "title": "Updated Book Title",
    "author": "Updated Author Name",
    "year": 2024,
    "genre": "Non-Fiction"
}
// Delete a book by ID
###
DELETE http://localhost:5000/api/books/4