// Endpoints

// Default endpoint for the client
###
GET http://localhost:5000/


// Get All books
###
GET http://localhost:5000/api/books

// Get a book by ID
###
GET http://localhost:5000/api/books/4

// Add a new book
###
POST http://localhost:5000/api/books
Content-Type: application/json

{
    "title": "New Book Title",
    "author": "New Author Name",
    "year": 2023,
    "genre": "Fiction"
}

// Update a book by ID
###
PUT http://localhost:5000/api/books/5
Content-Type: application/json

{
    "title": "Kotli in Action",
    "author": "John Doe",
    "year": 1999,
    "genre": "Programming"
}
// Delete a book by ID
###
DELETE http://localhost:5000/api/books/1